# Generated by Django 2.0.5 on 2018-05-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakepage', '0004_inscricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscricao',
            options={'ordering': ['criado_em'], 'verbose_name': 'nome', 'verbose_name_plural': 'nomes'},
        ),
    ]
