# Generated by Django 2.0.5 on 2018-05-17 20:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cakepage', '0005_auto_20180517_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'morango'), (2, 'chocolate'), (3, 'limao'), (4, 'maracuja'), (5, 'baunilha'), (6, 'queijo'), (7, 'goma')], max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Inscricao',
        ),
    ]
