# Generated by Django 2.0.5 on 2018-05-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakepage', '0006_auto_20180517_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(verbose_name='Data da resposta')),
            ],
            options={
                'verbose_name': 'Pool',
                'verbose_name_plural': 'Pools',
            },
        ),
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cakes',
                'verbose_name_plural': 'Cakess',
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='cakepool',
            name='cake',
            field=models.ManyToManyField(related_name='cake_pool', to='cakepage.Cakes'),
        ),
    ]
