# Generated by Django 2.0.5 on 2018-05-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakepage', '0007_auto_20180518_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakepool',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da resposta'),
        ),
    ]
