# Generated by Django 2.0.5 on 2018-05-21 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakepage', '0009_dicas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicas',
            options={'verbose_name': 'titulo', 'verbose_name_plural': 'titulos'},
        ),
    ]
